### ISSUE TITLE
Compile error with extension version 1.2.0

### ISSUE THREAD

**Issue by Userr017** [OPMerchantServices/op-payment-service-for-magento-2#120] opened 2020-09-04 11:33 UTC
I have installed latest extension version and there is compile issue

```
php bin/magento setup:di:compile        Compilation was started.
Area configuration aggregation... 5/8 [========>----]  62% 1 min 358.0 MiB
In ClassReader.php line 43:

  Class OpMerchantServices\SDK\Request\PaymentRequest does not exist


In ClassReader.php line 36:

  Class OpMerchantServices\SDK\Request\PaymentRequest does not exist
```

Extension version: 1.2.0
Magento: 2.3.5-p2

**Comment by roopesalminen** [comment] 2020-09-04 12:04
Hi!

Sorry to hear about the issue. Have you used composer to install the module or have you installed it directly under app/code directory?

**Comment by Userr017** [comment] 2020-09-04 12:14
Yes app/code/Op/Checkout. I restored back to version 1.9.0 and it works without issues but not 1.2.0.

**Comment by roopesalminen** [comment] 2020-09-04 12:23
Hi!

Unfortunately, from 1.2.0 onwards the module will only support composer installation, due to OP Payment Service PHP SDK being added as an external library. The library will not install correctly if you download the module in zip format.

We have updated the installation steps in the README file. I will paste them here as well.

1. Make sure that you have Magento file system owner rights.
2. Navigate to your Magento root folder on the command line and enter:
    _"composer require op-merchant-services/op-payment-service-for-magento-2:<latest_version> --no-update”_
3. If your credentials are asked, enter your Magento marketplace access keys.
4. Enter “composer update” on the command line
5. Run the following commands:
    php bin/magento module:enable Op_Checkout
    php bin/magento setup:upgrade
    php bin/magento setup:di:compile
    bin/magento setup:static-content:deploy

**Comment by roopesalminen** [comment] 2020-09-08 06:26
Closing the issue as this is not a bug but an intended feature.

**Closed by roopesalminen** 2020-09-08 06:26 UTC
Labels: bug
