### ISSUE TITLE
Order is created when no payment method is selected and Place Order button is clicked

### ISSUE THREAD

**Issue by kunzi** [OPMerchantServices/op-payment-service-for-magento-2#131] opened 2020-12-20 18:56 UTC
**Describe the bug**
At the Magento checkout's payment section if you don't select any specific payment method and click Place Order button, it creates an order with Pending Payment state and therefore reduces stock qty. You can create multiple orders in this way when you are at checkout page.

**To Reproduce**
Add a product to cart and continue to payment page of checkout and do not select any specific payment method of OP Payment Service's. Then click Place order button once or multiple times.

**Expected behavior**
It should not create an order at this point. It should only show info text that tells customer to choose a specific payment method.

**Additional context**
Magento 2.4.1. I did not try Vanilla.

**Comment by loueranta** [comment] 2020-12-22 08:25
@kunzi Thanks for reporting, we will look in to this.

**Comment by roopesalminen** [comment] 2021-01-25 14:45
Hello @kunzi!

We couldn't reproduce this bug with vanilla Magento 2.3.X or 2.4.X installations. Could you please provide information about any checkout related customizations or 3rd party modules in your store, as this will help in our investigations?

If you can also provide your store url, it will make reproducing the issue much faster.

Thank you,
Roope Salminen

**Comment by kunzi** [comment] 2021-01-25 20:31
Hello @roopesalminen 

Indeed I also tried it in another installation and there was no such problem. Then I disabled all checkout related extensions and changed the theme to Luma, but these changes had no effect and the problem still persisted. I have no idea why that happens. I can send you our test installation's url and also credentials if you want to test yourself (how do I send them to you?). The same problem is in the test installation.

However I noticed that there is a possibility to set this:  Skip payment method selection -> Yes
I think we might be able to bypass this problem.

But that brings another small problem as this text does not seem to be translatable:
You will be redirected to OP Payment Service.

How I can translate that?

Thanks!

**Comment by roopesalminen** [comment] 2021-01-28 06:26
Hello @kunzi!

Regarding the translation issue. Our apologies, we have completely missed the need for translation there and will get right on it. I assume you need Finnish translation for this?

If the bypass option works for you and the translation is sufficient, then there might be no need to investigate the problem further, but if you want us to continue working on the payment issue you can send the credentials and info to kumppanit@checkout.fi email.

Thank you, 
Roope Salminen

**Comment by kunzi** [comment] 2021-01-29 10:45
@roopesalminen Yes Finnish translation is needed.

I will send you the test installation credentials so you can check the problem. It would be nice to have the selection on the shop's checkout.

**Comment by roopesalminen** [comment] 2021-02-05 07:57
Hello @kunzi!

Did you send the credentials to kumppanit@checkout.fi yet?

-Roope

**Comment by kunzi** [comment] 2021-02-05 11:55
@roopesalminen Sorry for delay. I just sent the credentials!

**Comment by roopesalminen** [comment] 2021-02-26 06:45
@kunzi Sorry for late reply!

I was unable to reproduce the error in your environment. When trying to pay without choosing payment method, an error message shows up on the page similarly to vanilla Magento.

Could you perhaps send a screencast to display how the error reproduces for you?

**Comment by kunzi** [comment] 2021-02-26 12:42
@roopesalminen That is strange. Last time I checked in January I was able to reproduce the problem many times and it resulted many orders with pending payment status. Now the problem does not appear in test installation nor the production installation. Could it be that turning off and on the payment selection at checkout could have solved the issue? I hope it does not appear again.

**Comment by roopesalminen** [comment] 2021-03-12 07:18
Hello! @kunzi

Thanks for the information and good to hear that your checkout is now working well. Maybe turning off and on again helped :) I will close the issue for now, but if the problem persist you can open a new one.

Best regards,
Roope Salminen

**Closed by roopesalminen** 2021-03-12 07:18 UTC
Labels: bug
